version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis:alpine
  consumer:
    build: .
    command: ["python", "consumer.py"]
    depends_on:
      - redis
